package dev.miguelmachado.listapp

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import dev.miguelmachado.listapp.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
  // ActivityMainBinding is a class generated by the Android Gradle plugin. It is the layout name
  private lateinit var binding: ActivityMainBinding

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    binding = ActivityMainBinding.inflate(layoutInflater)
    setContentView(binding.root)

    val listView: RecyclerView = binding.lista

    listView.layoutManager = LinearLayoutManager(this)
    listView.adapter = ListAdapter()
  }
}
